### UsersRoute
// Creating new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Milica",
    "birthDate": "1999-09-16",
    "wishlist": ["62f7bb452d8adf6f210f0338"]
}

###
// Adding item to wish list of logged user
GET http://localhost:3000/users/addItemToWishList/62f7bc0f2d8adf6f210f033a

###
// Login
POST http://localhost:3000/users/login?name=Milica

###
// Logout
POST http://localhost:3000/users/logout

###
// Getting all upcoming birthdays
GET http://localhost:3000/users/upcomingBirthdays

### ItemsRoute
// Creating Item
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Book about ",
    "urlLink": "https://e7.pngegg.com/pngimages/953/151/png-clipart-recipe-cookbook-bolinhos-de-bacalhau-computer-icons-book-angle-kitchen-thumbnail.png"
}

###
// Deleting one item
DELETE http://localhost:3000/items/62fb52dcb7feedba26172fcc


